name         'p0deje-firefox'
version      '0.2.1'
source       'https://github.com/p0deje/puppet-display'
author       'p0deje'
license      'MIT'
summary      'Simple Firefox installation module'
description  'Simple Firefox installation module'
project_page 'https://github.com/p0deje/puppet-display'

dependency 'puppetlabs/apt'
